-- genre data (fixed spelling, added quotes/commas and correct table name)
INSERT INTO genre (genre)
VALUES
('animated'),
('b-movie'),
('comedy'),
('documentary'),
('drama'),
('family'),
('fantasy'),
('film noir'),
('holiday'),
('horror'),
('musical'),
('rom-com'),
('satire'),
('sci fi'),
('silent'),
('sports'),
('suspense'),
('thriller'),
('western');

-- DIRECTOR (normalized and quoted)
INSERT INTO director (first_name, last_name)
VALUES
('Ian','Ziering'),
('Tara','Reid'),
('John','Heard'),
('Cassandra','Scerbo'),
('Jason','Simmons'),
('Mike','Myers'),
('Eddie','Murphy'),
('Cameron','Diaz'),
('John','Lithgow'),
('Vincent','Cassel'),
('Michael Jai','White'),
('Salli','Richardson'),
('Byron','Mims'),
('Tommy','Davidson'),
('Kym','Whitley'),
('Robert','Downey Jr'),
('Chris','Hemsworth'),
('Scarlett','Johansson'),
('Samuel L','Jackson'),
('Josh','Brolin'),
('Robert','Redford'),
('Robert','Duvall'),
('Glenn','Close'),
('Kim','Bassinger'),
('Wilford','Brimley'),
('Mia','Farrow'),
('Bruce','Dern'),
('Karen','Black'),
('Scott','Wilson'),
('Lana','Turner'),
('John','Garfield'),
('Cecil','Kellaway'),
('Alan','Reed'),
('Audrey','Totter'),
('Leonardo','DiCaprio'),
('Carey','Mulligan'),
('Joel','Edgerton'),
('Tobey','Maguire'),
('Lisa','Adam'),
('Eartha','Kitt'),
('Sammy','Davis'),
('Frederick','O''Neal'),
('Rex','Ingram'),
('Rosetta','Lenoire'),
('Charlton','Heston'),
('Jeff','Goldblum'),
('Hope','Lange'),
('Steven','Keats'),
('Helen','Martin'),
('Jack','Lemmon'),
('Walter','Matthau'),
('Burgess','Meredith'),
('Ann-Margret', NULL),
('Ossie','Davis'),
('Sophia','Loren'),
('Diana','Ross'),
('Michael','Jackson'),
('Nipsey','Russell'),
('Ted','Ross'),
('Richard','Pryor'),
('Breno','Mello'),
('Marpessa','Dawn'),
('Lourdes','De Oliveira'),
('Lea','Garcia'),
('Adhemar Ferreira','Da Silva'),
('Mel','Brooks'),
('John','Candy'),
('Bill','Pullman'),
('Rick','Moranis'),
('Daphne','Zuniga');

-- PRODUCTION COMPANIES (normalized and quoted)
INSERT INTO production (production)
VALUES
('Asylum'),
('DreamWorks'),
('Destination Films'),
('Marvel Studios'),
('Tri-Star Pictures'),
('Paramount'),
('Loew''s'),
('Warner Bros'),
('Longridge Enterprises'),
('Dino De Laurentiis'),
('Universal Pictures'),
('Dispat Films'),
('MGM');

-- STREAMING_PLATFORM (normalized and quoted)
INSERT INTO streaming_platform (platform)
VALUES
('Apple TV'),
('Crackle'),
('CRTV'),
('Disney+'),
('Freevee'),
('HBO Max'),
('Hulu'),
('Netflix'),
('Paramount+'),
('Peacock'),
('Prime Video'),
('Roku'),
('Starz'),
('Tubi'),
('YouTube');


INSERT INTO movie (title, rating, runtime, nationality, yr_released, budget, gross, production_id, showing, poster)
VALUES
('Sharknado','NR','01:26:00','USA',2013,1000000,5000000,1,'direct-to-tv','sharknado.jpg'),
('Shrek','PG','01:30:00','USA',2001,60000000,488977919,2,'theater','shrek.jpg'),
('Black Dynamite','R','01:24:00','USA',2009,2900000,296557,3,'theater','black_dynamite.jpg'),
('Avengers: Endgame','PG-13','03:01:00','USA',2019,356000000,2799439100,4,'theater','endgame.jpg'),
('The Natural','PG','02:18:00','USA',1984,28000000,47951979,5,'theater','natural.jpg'),
('The Great Gatsby','PG','02:24:00','USA',1974,6500000,20563273,6,'theater','great_gatsby74.jpg'),
('The Postman Always Rings Twice','NR','01:53:00','USA',1946,1683000,NULL,7,'theater','postman_rings_twice.jpg'),
('The Great Gatsby','PG-13','02:23:00','USA',2013,105000000,353660028,8,'theater','great_gatsby13.jpg'),
('Anna Lucasta','NR','01:37:00','USA',1958,NULL,NULL,9,'theater','anna_lucasta.jpg'),
('Death Wish','R','01:33:00','USA',1974,3000000,22000000,10,'theater','death_wish.jpg'),
('Grumpy Old Men','PG-13','01:43:00','USA',1993,NULL,70172621,8,'theater','grumpy_old_men.jpg'),
('Grumpier Old Men','PG-13','01:41:00','USA',1995,25000000,71518503,8,'theater','grumpier_old_men.jpg'),
('The Wiz','G','02:14:00','USA',1978,24000000,21049819,11,'theater','the_wiz.jpg'),
('Black Orpheus','PG','01:40:00','BRA',1959,NULL,NULL,12,'theater','black_orpheus.jpg'),
('Spaceballs','PG','01:36:00','USA',1987,22700000,38120460,13,'theater','spaceballs.jpg');