DROP DATABASE IF EXISTS myalbumdb;
CREATE DATABASE myalbumdb;
USE myalbumdb;

CREATE TABLE artist(
    
    CONSTRAINT pk_artist PRIMARY KEY (artist_id)
);

CREATE TABLE band(
    band_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    band VARCHAR(40),
    CONSTRAINT pk_band PRIMARY KEY (band_id)
);

CREATE TABLE label(
    label_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    label VARCHAR(40),
    CONSTRAINT pk_label PRIMARY KEY (label_id)
);

CREATE TABLE album(
    album_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    artist_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    fName VARCHAR(40),
    lName VARCHAR(40),title VARCHAR(60),
    artist_id SMALLINT UNSIGNED NOT NULL,
    band_id SMALLINT UNSIGNED NOT NULL,
    label_id SMALLINT UNSIGNED NOT NULL,
    yr_released YEAR,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    CONSTRAINT pk_album PRIMARY KEY (album_id),
    CONSTRAINT fk_artist FOREIGN KEY (artist_id) REFERENCES artist(artist_id),
    CONSTRAINT fk_band FOREIGN KEY (band_id) REFERENCES band(band_id),
    CONSTRAINT fk_label FOREIGN KEY (label_id) REFERENCES label(label_id)
);


---ALTERATIONS
ALTER TABLE artist 
ADD date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE band 
ADD date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE label
ADD date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
